# Generated by Django 4.2.3 on 2023-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('pub_date', models.DateField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
