# Generated by Django 4.2.3 on 2023-07-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Food',
        ),
    ]
