# Generated by Django 4.2.3 on 2023-07-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_todo_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
    ]
