# Generated by Django 4.2.3 on 2023-07-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
