# Generated by Django 4.2.3 on 2023-07-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='genre',
        ),
    ]
